version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - ./server:/usr/src/app
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=Gtatropa123*
      - DB_NAME=to_do_app
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Gtatropa123*
      MYSQL_DATABASE: to_do_app
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data: